version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: comentarios
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: endreocordeiro/desafio-devops:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: comentarios
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"

volumes:
  postgres_data:
