global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["35.208.45.64:8000"]

  - job_name: "gce-node-exporter"
    static_configs:
      - targets: ["35.208.45.64:9100"]