global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["34.10.228.102:8000"]

  - job_name: "gce-node-exporter"
    static_configs:
      - targets: ["34.10.228.102:9100"]